### ISSUE TITLE
[Bug]: When const variable is negative prompt to display as NaN

### ISSUE THREAD

**Issue by a1967629423** [copytime/UnrealScript-Language-Service#1]
### Describe the bug

如题

**Comment by copytime** [comment]
有符号的数字被解析为了多个 token：
`const fpp = -45;`
上面代码的 `-45`  解析为 `-` 和 `45`。
而获取 Tooltips 的时候求值阶段只使用了起始 token 的 text 值。

`parseInt('-')`
导致 NaN

**Comment by copytime** [comment]
Fixed in 330cb064e1cb96618214f9e4231dc540c298c284
